export interface FigletFontCategory {
  label: string;
  fonts: string[];
}

export const FIGLET_FONTS_BY_CATEGORY: FigletFontCategory[] = [
  {
    label: '3D',
    fonts: [
      '3D Diagonal',
      '3D-ASCII',
      'Alpha',
      'Big Money-ne',
      'Big Money-nw',
      'Big Money-se',
      'Big Money-sw',
      'Chiseled',
      'Henry 3D',
      'Impossible',
      'Isometric1',
      'Isometric2',
      'Isometric3',
      'Isometric4',
      'Larry 3D',
      'Patorjk-HeX',
  "Patorjk's Cheese",
      'Slant Relief',
      'Small Isometric1',
      'Sub-Zero',
      'Swamp Land',
    ],
  },
  {
    label: 'ANSI',
    fonts: [
      'ANSI Shadow',
      'Bloody',
      'Calvin S',
      'Delta Corps Priest 1',
      'DOS Rebel',
      'Electronic',
      'Elite',
      'Pagga',
      'The Edge',
      'THIS',
    ],
  },
  {
    label: 'Banner',
    fonts: [
      '3x5',
      'Alphabet',
      'Banner',
      'Banner3',
      'Banner3-D',
      'Banner4',
      'Caligraphy',
      'Caligraphy2',
      'Old Banner',
    ],
  },
  {
    label: 'Block',
    fonts: ['Block', 'Lean', 'Small Shadow'],
  },
  {
    label: 'Codes',
    fonts: [
      'Binary',
      'Decimal',
      'DWhistled',
      'Hex',
      'ICL-1900',
      'Morse',
      'Octal',
      'Rot13',
    ],
  },
  {
    label: 'Contrast',
    fonts: [
      'Bright',
      'Contrast',
      'OS2',
      'Peaks Slant',
      'Relief',
      'Relief2',
      'Reverse',
      'Ticks',
      'Ticks Slant',
    ],
  },
  {
    label: 'Dingbats',
    fonts: ['Efti Chess', 'Efti Wall', 'Fun Face', 'Fun Faces', 'Hieroglyphs'],
  },
  {
    label: 'Foreign Languages',
    fonts: [
      'Jerusalem',
      'Katakana',
      'Moscow',
      'Mshebrew210',
      'NT Greek',
      'Runic',
      'Runyc',
      'Small Tengwar',
      'Tengwar',
    ],
  },
  {
    label: 'Framed',
    fonts: [
      'Bear',
      'Bubble',
      'Digital',
      'Heart Left',
      'Heart Right',
      'Keyboard',
      'Puzzle',
      'Pyramid',
      'Small Keyboard',
    ],
  },
  {
    label: 'Line',
    fonts: [
      '5 Line Oblique',
      'Acrobatic',
      'AMC 3 Line',
      'AMC Slider',
      'ASCII New Roman',
      'Bell',
      'Bigfig',
      'Contessa',
      'Cyberlarge',
      'Cybermedium',
      'Cybersmall',
      'Cygnet',
      'Four Tops',
      'Gothic',
      'Italic',
      'JS Capital Curves',
      'JS Stick Letters',
      'LCD',
      'Madrid',
      'Maxfour',
      'Mini',
      'Muzzle',
      'Pepper',
      'Short',
      'Stampatello',
      'Stick Letters',
      'Straight',
      'Swan',
      'Thin',
      'Thorned',
      'Three Point',
      'Tinker-Toy',
      'Tombstone',
      'Tsalagi',
      'Two Point',
      'Wavy',
      'Weird',
    ],
  },
  {
    label: 'Miscellaneous',
    fonts: [
      'AMC Tubes',
      'Efti Italic',
      'Efti Piti',
      'Efti Water',
      'Ghoulish',
      'Gradient',
      'Mnemonic',
      'Slide',
      'Stampate',
      'Star Strips',
      'Tanja',
      'Test1',
      'Thick',
      'Tiles',
      'Tubular',
    ],
  },
  {
    label: 'One-line',
    fonts: ['1Row', 'B1FF', 'Benjamin', 'Term', 'Wow'],
  },
  {
    label: 'Outline',
    fonts: [
      'AMC Razor',
      'AMC Razor2',
      'AMC Thin',
      'AMC Untitled',
      'Avatar',
      'Big',
      'Braced',
      'Broadway KB',
      'Bulbhead',
      'Chunky',
      'Crawford',
      'Crawford2',
      'Crazy',
      'Cricket',
      'Dancing Font',
      'Doom',
      'Double',
      'Double Shorts',
      'Dr Pepper',
      'Efti Font',
      'Efti Robot',
      'Epic',
      'Fire Font-k',
      'Fire Font-s',
      'Flower Power',
      'Fuzzy',
      'Ghost',
      'Glenyn',
      'Goofy',
      'Graceful',
      'Graffiti',
      'Greek',
      'Ivrit',
      'Jacky',
      'JS Block Letters',
      'JS Bracket Letters',
      'Lil Devil',
      'Line Blocks',
      'Linux',
      'Merlin1',
      'Merlin2',
      'Modular',
      'Ogre',
      'Puffy',
      'Rammstein',
      'Rectangles',
      'Red Phoenix',
      'Rounded',
      'Serifcap',
      'Shadow',
      'Slant',
      'Small',
      'Small Caps',
      'Small Slant',
      'Soft',
      'Speed',
      'Spliff',
      'Stacey',
      'Standard',
      'Star Wars',
      'Stforek',
      'Stop',
      'Stronger Than All',
      'Sweet',
      'Train',
      'Twisted',
      'Varsity',
      'Wet Letter',
    ],
  },
  {
    label: 'Pattern',
    fonts: [
      'Arrows',
      'Barbwire',
      'Blocks',
      'Cards',
      'Catwalk',
      'Coinstak',
      'Diamond',
      'Dot Matrix',
      'Nipples',
      'Pawp',
      'Peaks',
      'Stellar',
    ],
  },
  {
    label: 'Script',
    fonts: [
      'Cola',
      'Cursive',
      'Diet Cola',
      'Hollywood',
      'Invita',
      'JS Cursive',
      'NScript',
      'NV Script',
      'Santa Clara',
      'Script',
      'Shimrod',
      'SL Script',
      'Small Script',
    ],
  },
  {
    label: 'Solid',
    fonts: [
      '4Max',
      'Alligator',
      'Alligator2',
      'AMC AAA01',
      'AMC Neko',
      'AMC Slash',
      'Basic',
      'Bolger',
      'Broadway',
      'Colossal',
      'Computer',
      'Cosmike',
      'Def Leppard',
      'Doh',
      'Fender',
      'Filter',
      'Fraktur',
      'Georgi16',
      'Georgia11',
      'Jazmine',
      'Kban',
      'Letters',
      'Lockergnome',
      'Marquee',
      'Nancyj-Fancy',
      'Nancyj-Improved',
      'Nancyj-Underlined',
      'O8',
      'Pebbles',
      'Poison',
      'Roman',
      'Rowan Cap',
      'Rozzo',
      'S Blood',
      'Small Poison',
      'Trek',
      'Univers',
      'USA Flag',
      'Whimsy',
    ],
  },
  {
    label: 'Turned',
    fonts: [
      'AMC 3 Liv1',
      'Flipped',
      'Horizontal Left',
      'Horizontal Right',
      'Knob',
      'Mirror',
      'Rotated',
    ],
  },
];

export const ALL_FIGLET_FONTS: string[] = FIGLET_FONTS_BY_CATEGORY.flatMap((category) => category.fonts);
